# Generated by Django 4.1.7 on 2023-03-31 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_enrollment_durdate_enrollment_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='DurDate',
            new_name='DueDate',
        ),
    ]
